apiVersion: v1
kind: ConfigMap
metadata:
  name: website-data
data:
  index.html: |
    <html>
    <body>
    <h1>Hello world!</h1>
    </body>
    </html>

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      volumeMounts:
        - name: website
          mountPath: /usr/share/nginx/html
  volumes:
    - name: website
      configMap:
        name: website-data